# Generated by Django 2.2.6 on 2020-01-05 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='abc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='abc2',
            field=models.CharField(default='kkk', max_length=100),
        ),
    ]
