# Generated by Django 2.2.6 on 2020-01-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0007_auto_20200105_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
